#!/bin/sh

templates=$(dirname $0)/templates

infrastructure=$1

shift

if [ "$infrastructure" != "openstack" ] && \
    [ "$infrastructure" != "warden" ] ; then
  echo "usage: ./generate_deployment_manifest <warden|openstack> [stubs...]"
  exit 1
fi

spiff merge \
  $templates/cf-cassandra-broker-template.yml \
  $templates/cf-infrastructure-${infrastructure}.yml \
  $*
