director_uuid: YOUR_DIRECTOR_UUID

networks:
- name: services
  type: manual
  subnets:
  - range: 10.10.38.0/24
    gateway: 10.10.38.1
    reserved: [ 10.10.38.2 - 10.10.38.4, 10.10.38.254 ]
    static: [ 10.10.38.6 - 10.10.38.8 ]
    dns: [ 10.10.0.6 ]
    cloud_properties:
      subnet: subnet-id
      security_groups: [ security-group-name ]

meta:
  availability_zone: YOUR_SUBNET_AVAILABILITY_ZONE
  environment: YOUR_ENVIRONMENT_NAME
  nats:
    user: nats
    password: NATS_PASSWORD_FROM_CF_RELEASE
    machines: [ 10.10.80.11 ]
    port: 4222
  cf:
    # these come from your cf-release manifest
    admin_username: YOUR_CF_ADMIN_USERNAME
    admin_password: YOUR_CF_ADMIN_PASSWORD
    skip_ssl_validation: true
    external_domain: YOUR_CF_SYSTEM_DOMAIN
    apps_domain: YOUR_CF_APPS_DOMAIN

jobs:
  - name: cf-cassandra-broker
    properties:
      username: A_USERNAME_YOU_MAKE_UP
      password: A_PASSWORD_YOU_MAKE_UP

      cassandra:
        nodes: LIST_OF_CASSANDRA_NODES
        username: CASSNADRA_SUPERUSER_USERNAME
        password: CASSNADRA_SUPERUSER_PASSWORD
